version: "3.7"

services:

  ui:
    image: registry.dev.n18.an.cnav/scn-design-22/scn-design-22:${VERSION:-latest}
    networks:
      - front-network
    deploy:
      labels:
          - "traefik.docker.network=front-network"
          - "traefik.http.routers.scn-design-22-${NEWCOLOR:-blue}.priority=10"
          - "traefik.http.routers.scn-design-22-${NEWCOLOR:-blue}.rule=HostRegexp(`scn.{domain:[a-z0-9\\.]+}`)"
          
         # - "traefik.http.routers.scn-design-22-${NEWCOLOR:-blue}.rule=Host(`slt03092.dev.n18.an.cnav`)"
          - "traefik.http.services.scn-design-22-${NEWCOLOR:-blue}.loadbalancer.server.port=80"

networks:

  front-network:
    external: true
    